//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Poc and Personal\AntlrActions\WordCount.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


/* If we have package declarations, it should go here. */
using System;
using Antlr4.Runtime;


using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class WordCountLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		WORD=1, WS=2, NL=3;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"WORD", "WS", "NL", "LETTER"
	};


	  public int wordcount = 0;
	  public int linecount = 0;

	  public static void Main(string[] args) {
	    var input = new AntlrInputStream("Hello world\nIt's a lexer.\n");
	    Token t;
	    var lexer = new WordCountLexer(input);
	    while((t=lexer.NextToken() != Token.EOF_TOKEN && t.GetType() >= 0)
	    {
	    ;
	    }

	   Console.WriteLine("Total words:" + lexer.wordcount);
	   Console.WriteLine("Total lines:" + lexer.linecount);
	  }


	public WordCountLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public WordCountLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, null, "'\n'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "WORD", "WS", "NL"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "WordCount.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static WordCountLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	public override void Action(RuleContext _localctx, int ruleIndex, int actionIndex) {
		switch (ruleIndex) {
		case 0 : WORD_action(_localctx, actionIndex); break;
		case 2 : NL_action(_localctx, actionIndex); break;
		}
	}
	private void WORD_action(RuleContext _localctx, int actionIndex) {
		switch (actionIndex) {
		case 0: this.wordcount ++; break;
		}
	}
	private void NL_action(RuleContext _localctx, int actionIndex) {
		switch (actionIndex) {
		case 1: this.linecount ++; break;
		}
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x5', '\x1E', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x3', '\x2', '\x6', '\x2', '\r', '\n', '\x2', '\r', '\x2', '\xE', 
		'\x2', '\xE', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x6', '\x3', 
		'\x14', '\n', '\x3', '\r', '\x3', '\xE', '\x3', '\x15', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', 
		'\x3', '\x5', '\x2', '\x2', '\x6', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', 
		'\t', '\x2', '\x3', '\x2', '\x4', '\x4', '\x2', '\v', '\v', '\"', '\"', 
		'\x4', '\x2', '\v', '\f', '\"', '\"', '\x2', '\x1E', '\x2', '\x3', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\a', '\x3', '\x2', '\x2', '\x2', '\x3', '\f', '\x3', '\x2', '\x2', '\x2', 
		'\x5', '\x13', '\x3', '\x2', '\x2', '\x2', '\a', '\x19', '\x3', '\x2', 
		'\x2', '\x2', '\t', '\x1C', '\x3', '\x2', '\x2', '\x2', '\v', '\r', '\x5', 
		'\t', '\x5', '\x2', '\f', '\v', '\x3', '\x2', '\x2', '\x2', '\r', '\xE', 
		'\x3', '\x2', '\x2', '\x2', '\xE', '\f', '\x3', '\x2', '\x2', '\x2', '\xE', 
		'\xF', '\x3', '\x2', '\x2', '\x2', '\xF', '\x10', '\x3', '\x2', '\x2', 
		'\x2', '\x10', '\x11', '\b', '\x2', '\x2', '\x2', '\x11', '\x4', '\x3', 
		'\x2', '\x2', '\x2', '\x12', '\x14', '\t', '\x2', '\x2', '\x2', '\x13', 
		'\x12', '\x3', '\x2', '\x2', '\x2', '\x14', '\x15', '\x3', '\x2', '\x2', 
		'\x2', '\x15', '\x13', '\x3', '\x2', '\x2', '\x2', '\x15', '\x16', '\x3', 
		'\x2', '\x2', '\x2', '\x16', '\x17', '\x3', '\x2', '\x2', '\x2', '\x17', 
		'\x18', '\b', '\x3', '\x3', '\x2', '\x18', '\x6', '\x3', '\x2', '\x2', 
		'\x2', '\x19', '\x1A', '\a', '\f', '\x2', '\x2', '\x1A', '\x1B', '\b', 
		'\x4', '\x4', '\x2', '\x1B', '\b', '\x3', '\x2', '\x2', '\x2', '\x1C', 
		'\x1D', '\n', '\x3', '\x2', '\x2', '\x1D', '\n', '\x3', '\x2', '\x2', 
		'\x2', '\x5', '\x2', '\xE', '\x15', '\x5', '\x3', '\x2', '\x2', '\b', 
		'\x2', '\x2', '\x3', '\x4', '\x3',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
