//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Poc and Personal\AntlrDraw\Draw.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="DrawParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IDrawListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DrawParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] DrawParser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DrawParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] DrawParser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>init</c>
	/// labeled alternative in <see cref="DrawParser.stm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInit([NotNull] DrawParser.InitContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>init</c>
	/// labeled alternative in <see cref="DrawParser.stm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInit([NotNull] DrawParser.InitContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>up</c>
	/// labeled alternative in <see cref="DrawParser.stm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUp([NotNull] DrawParser.UpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>up</c>
	/// labeled alternative in <see cref="DrawParser.stm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUp([NotNull] DrawParser.UpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>down</c>
	/// labeled alternative in <see cref="DrawParser.stm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDown([NotNull] DrawParser.DownContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>down</c>
	/// labeled alternative in <see cref="DrawParser.stm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDown([NotNull] DrawParser.DownContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>left</c>
	/// labeled alternative in <see cref="DrawParser.stm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLeft([NotNull] DrawParser.LeftContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>left</c>
	/// labeled alternative in <see cref="DrawParser.stm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLeft([NotNull] DrawParser.LeftContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>right</c>
	/// labeled alternative in <see cref="DrawParser.stm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRight([NotNull] DrawParser.RightContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>right</c>
	/// labeled alternative in <see cref="DrawParser.stm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRight([NotNull] DrawParser.RightContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>draw</c>
	/// labeled alternative in <see cref="DrawParser.stm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDraw([NotNull] DrawParser.DrawContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>draw</c>
	/// labeled alternative in <see cref="DrawParser.stm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDraw([NotNull] DrawParser.DrawContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>display</c>
	/// labeled alternative in <see cref="DrawParser.stm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDisplay([NotNull] DrawParser.DisplayContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>display</c>
	/// labeled alternative in <see cref="DrawParser.stm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDisplay([NotNull] DrawParser.DisplayContext context);
}
