//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Poc and Personal\AntlrDraw\HelloAntlr.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class HelloAntlrLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, SEMI=2, ID=3, WS=4;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "SEMI", "ID", "WS"
	};


	public HelloAntlrLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public HelloAntlrLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'Hello'", "';'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, "SEMI", "ID", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "HelloAntlr.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static HelloAntlrLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x6', '\x1F', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x6', 
		'\x4', '\x15', '\n', '\x4', '\r', '\x4', '\xE', '\x4', '\x16', '\x3', 
		'\x5', '\x6', '\x5', '\x1A', '\n', '\x5', '\r', '\x5', '\xE', '\x5', '\x1B', 
		'\x3', '\x5', '\x3', '\x5', '\x2', '\x2', '\x6', '\x3', '\x3', '\x5', 
		'\x4', '\a', '\x5', '\t', '\x6', '\x3', '\x2', '\x4', '\x3', '\x2', '\x43', 
		'|', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', '\x2', ' ', '\x2', 
		'\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', 
		'\x2', '\x2', '\x3', '\v', '\x3', '\x2', '\x2', '\x2', '\x5', '\x11', 
		'\x3', '\x2', '\x2', '\x2', '\a', '\x14', '\x3', '\x2', '\x2', '\x2', 
		'\t', '\x19', '\x3', '\x2', '\x2', '\x2', '\v', '\f', '\a', 'J', '\x2', 
		'\x2', '\f', '\r', '\a', 'g', '\x2', '\x2', '\r', '\xE', '\a', 'n', '\x2', 
		'\x2', '\xE', '\xF', '\a', 'n', '\x2', '\x2', '\xF', '\x10', '\a', 'q', 
		'\x2', '\x2', '\x10', '\x4', '\x3', '\x2', '\x2', '\x2', '\x11', '\x12', 
		'\a', '=', '\x2', '\x2', '\x12', '\x6', '\x3', '\x2', '\x2', '\x2', '\x13', 
		'\x15', '\t', '\x2', '\x2', '\x2', '\x14', '\x13', '\x3', '\x2', '\x2', 
		'\x2', '\x15', '\x16', '\x3', '\x2', '\x2', '\x2', '\x16', '\x14', '\x3', 
		'\x2', '\x2', '\x2', '\x16', '\x17', '\x3', '\x2', '\x2', '\x2', '\x17', 
		'\b', '\x3', '\x2', '\x2', '\x2', '\x18', '\x1A', '\t', '\x3', '\x2', 
		'\x2', '\x19', '\x18', '\x3', '\x2', '\x2', '\x2', '\x1A', '\x1B', '\x3', 
		'\x2', '\x2', '\x2', '\x1B', '\x19', '\x3', '\x2', '\x2', '\x2', '\x1B', 
		'\x1C', '\x3', '\x2', '\x2', '\x2', '\x1C', '\x1D', '\x3', '\x2', '\x2', 
		'\x2', '\x1D', '\x1E', '\b', '\x5', '\x2', '\x2', '\x1E', '\n', '\x3', 
		'\x2', '\x2', '\x2', '\x5', '\x2', '\x16', '\x1B', '\x3', '\b', '\x2', 
		'\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
