//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Poc and Personal\AntlrToAsm\Simple.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class SimpleLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, MUL=12, DIV=13, MOD=14, ADD=15, SUB=16, ID=17, INT=18, 
		WS=19;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "MUL", "DIV", "MOD", "ADD", "SUB", "ID", "INT", "WS"
	};


	public SimpleLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public SimpleLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "':='", "'print'", "'if'", "'then'", "'while'", "'do'", "'begin'", 
		"'end'", "';'", "'('", "')'", "'*'", "'/'", "'mod'", "'+'", "'-'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		"MUL", "DIV", "MOD", "ADD", "SUB", "ID", "INT", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Simple.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static SimpleLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x15', 'p', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\v', 
		'\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x12', '\x6', '\x12', '\x61', '\n', '\x12', '\r', '\x12', '\xE', '\x12', 
		'\x62', '\x3', '\x13', '\x6', '\x13', '\x66', '\n', '\x13', '\r', '\x13', 
		'\xE', '\x13', 'g', '\x3', '\x14', '\x6', '\x14', 'k', '\n', '\x14', '\r', 
		'\x14', '\xE', '\x14', 'l', '\x3', '\x14', '\x3', '\x14', '\x2', '\x2', 
		'\x15', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', 
		'\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', 
		'\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', 
		'\x12', '#', '\x13', '%', '\x14', '\'', '\x15', '\x3', '\x2', '\x5', '\x4', 
		'\x2', '\x43', '\\', '\x63', '|', '\x3', '\x2', '\x32', ';', '\x5', '\x2', 
		'\v', '\f', '\xF', '\xF', '\"', '\"', '\x2', 'r', '\x2', '\x3', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x3', ')', '\x3', '\x2', 
		'\x2', '\x2', '\x5', ',', '\x3', '\x2', '\x2', '\x2', '\a', '\x32', '\x3', 
		'\x2', '\x2', '\x2', '\t', '\x35', '\x3', '\x2', '\x2', '\x2', '\v', ':', 
		'\x3', '\x2', '\x2', '\x2', '\r', '@', '\x3', '\x2', '\x2', '\x2', '\xF', 
		'\x43', '\x3', '\x2', '\x2', '\x2', '\x11', 'I', '\x3', '\x2', '\x2', 
		'\x2', '\x13', 'M', '\x3', '\x2', '\x2', '\x2', '\x15', 'O', '\x3', '\x2', 
		'\x2', '\x2', '\x17', 'Q', '\x3', '\x2', '\x2', '\x2', '\x19', 'S', '\x3', 
		'\x2', '\x2', '\x2', '\x1B', 'U', '\x3', '\x2', '\x2', '\x2', '\x1D', 
		'W', '\x3', '\x2', '\x2', '\x2', '\x1F', '[', '\x3', '\x2', '\x2', '\x2', 
		'!', ']', '\x3', '\x2', '\x2', '\x2', '#', '`', '\x3', '\x2', '\x2', '\x2', 
		'%', '\x65', '\x3', '\x2', '\x2', '\x2', '\'', 'j', '\x3', '\x2', '\x2', 
		'\x2', ')', '*', '\a', '<', '\x2', '\x2', '*', '+', '\a', '?', '\x2', 
		'\x2', '+', '\x4', '\x3', '\x2', '\x2', '\x2', ',', '-', '\a', 'r', '\x2', 
		'\x2', '-', '.', '\a', 't', '\x2', '\x2', '.', '/', '\a', 'k', '\x2', 
		'\x2', '/', '\x30', '\a', 'p', '\x2', '\x2', '\x30', '\x31', '\a', 'v', 
		'\x2', '\x2', '\x31', '\x6', '\x3', '\x2', '\x2', '\x2', '\x32', '\x33', 
		'\a', 'k', '\x2', '\x2', '\x33', '\x34', '\a', 'h', '\x2', '\x2', '\x34', 
		'\b', '\x3', '\x2', '\x2', '\x2', '\x35', '\x36', '\a', 'v', '\x2', '\x2', 
		'\x36', '\x37', '\a', 'j', '\x2', '\x2', '\x37', '\x38', '\a', 'g', '\x2', 
		'\x2', '\x38', '\x39', '\a', 'p', '\x2', '\x2', '\x39', '\n', '\x3', '\x2', 
		'\x2', '\x2', ':', ';', '\a', 'y', '\x2', '\x2', ';', '<', '\a', 'j', 
		'\x2', '\x2', '<', '=', '\a', 'k', '\x2', '\x2', '=', '>', '\a', 'n', 
		'\x2', '\x2', '>', '?', '\a', 'g', '\x2', '\x2', '?', '\f', '\x3', '\x2', 
		'\x2', '\x2', '@', '\x41', '\a', '\x66', '\x2', '\x2', '\x41', '\x42', 
		'\a', 'q', '\x2', '\x2', '\x42', '\xE', '\x3', '\x2', '\x2', '\x2', '\x43', 
		'\x44', '\a', '\x64', '\x2', '\x2', '\x44', '\x45', '\a', 'g', '\x2', 
		'\x2', '\x45', '\x46', '\a', 'i', '\x2', '\x2', '\x46', 'G', '\a', 'k', 
		'\x2', '\x2', 'G', 'H', '\a', 'p', '\x2', '\x2', 'H', '\x10', '\x3', '\x2', 
		'\x2', '\x2', 'I', 'J', '\a', 'g', '\x2', '\x2', 'J', 'K', '\a', 'p', 
		'\x2', '\x2', 'K', 'L', '\a', '\x66', '\x2', '\x2', 'L', '\x12', '\x3', 
		'\x2', '\x2', '\x2', 'M', 'N', '\a', '=', '\x2', '\x2', 'N', '\x14', '\x3', 
		'\x2', '\x2', '\x2', 'O', 'P', '\a', '*', '\x2', '\x2', 'P', '\x16', '\x3', 
		'\x2', '\x2', '\x2', 'Q', 'R', '\a', '+', '\x2', '\x2', 'R', '\x18', '\x3', 
		'\x2', '\x2', '\x2', 'S', 'T', '\a', ',', '\x2', '\x2', 'T', '\x1A', '\x3', 
		'\x2', '\x2', '\x2', 'U', 'V', '\a', '\x31', '\x2', '\x2', 'V', '\x1C', 
		'\x3', '\x2', '\x2', '\x2', 'W', 'X', '\a', 'o', '\x2', '\x2', 'X', 'Y', 
		'\a', 'q', '\x2', '\x2', 'Y', 'Z', '\a', '\x66', '\x2', '\x2', 'Z', '\x1E', 
		'\x3', '\x2', '\x2', '\x2', '[', '\\', '\a', '-', '\x2', '\x2', '\\', 
		' ', '\x3', '\x2', '\x2', '\x2', ']', '^', '\a', '/', '\x2', '\x2', '^', 
		'\"', '\x3', '\x2', '\x2', '\x2', '_', '\x61', '\t', '\x2', '\x2', '\x2', 
		'`', '_', '\x3', '\x2', '\x2', '\x2', '\x61', '\x62', '\x3', '\x2', '\x2', 
		'\x2', '\x62', '`', '\x3', '\x2', '\x2', '\x2', '\x62', '\x63', '\x3', 
		'\x2', '\x2', '\x2', '\x63', '$', '\x3', '\x2', '\x2', '\x2', '\x64', 
		'\x66', '\t', '\x3', '\x2', '\x2', '\x65', '\x64', '\x3', '\x2', '\x2', 
		'\x2', '\x66', 'g', '\x3', '\x2', '\x2', '\x2', 'g', '\x65', '\x3', '\x2', 
		'\x2', '\x2', 'g', 'h', '\x3', '\x2', '\x2', '\x2', 'h', '&', '\x3', '\x2', 
		'\x2', '\x2', 'i', 'k', '\t', '\x4', '\x2', '\x2', 'j', 'i', '\x3', '\x2', 
		'\x2', '\x2', 'k', 'l', '\x3', '\x2', '\x2', '\x2', 'l', 'j', '\x3', '\x2', 
		'\x2', '\x2', 'l', 'm', '\x3', '\x2', '\x2', '\x2', 'm', 'n', '\x3', '\x2', 
		'\x2', '\x2', 'n', 'o', '\b', '\x14', '\x2', '\x2', 'o', '(', '\x3', '\x2', 
		'\x2', '\x2', '\x6', '\x2', '\x62', 'g', 'l', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
