//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Poc and Personal\AntlrAsm\MyLanguageV0Code.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="MyLanguageV0CodeParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IMyLanguageV0CodeVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageV0CodeParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] MyLanguageV0CodeParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageV0CodeParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] MyLanguageV0CodeParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageV0CodeParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] MyLanguageV0CodeParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageV0CodeParser.ifstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfstmt([NotNull] MyLanguageV0CodeParser.IfstmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageV0CodeParser.printstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintstmt([NotNull] MyLanguageV0CodeParser.PrintstmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageV0CodeParser.assignstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignstmt([NotNull] MyLanguageV0CodeParser.AssignstmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageV0CodeParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] MyLanguageV0CodeParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageV0CodeParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] MyLanguageV0CodeParser.TermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageV0CodeParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] MyLanguageV0CodeParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageV0CodeParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInteger([NotNull] MyLanguageV0CodeParser.IntegerContext context);
}
