//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Poc and Personal\AntlrAsm\MyLanguageV0Code.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IMyLanguageV0CodeListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class MyLanguageV0CodeBaseListener : IMyLanguageV0CodeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyLanguageV0CodeParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] MyLanguageV0CodeParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyLanguageV0CodeParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] MyLanguageV0CodeParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyLanguageV0CodeParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] MyLanguageV0CodeParser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyLanguageV0CodeParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] MyLanguageV0CodeParser.DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyLanguageV0CodeParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] MyLanguageV0CodeParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyLanguageV0CodeParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] MyLanguageV0CodeParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyLanguageV0CodeParser.ifstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfstmt([NotNull] MyLanguageV0CodeParser.IfstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyLanguageV0CodeParser.ifstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfstmt([NotNull] MyLanguageV0CodeParser.IfstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyLanguageV0CodeParser.printstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrintstmt([NotNull] MyLanguageV0CodeParser.PrintstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyLanguageV0CodeParser.printstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrintstmt([NotNull] MyLanguageV0CodeParser.PrintstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyLanguageV0CodeParser.assignstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignstmt([NotNull] MyLanguageV0CodeParser.AssignstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyLanguageV0CodeParser.assignstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignstmt([NotNull] MyLanguageV0CodeParser.AssignstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyLanguageV0CodeParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] MyLanguageV0CodeParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyLanguageV0CodeParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] MyLanguageV0CodeParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyLanguageV0CodeParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] MyLanguageV0CodeParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyLanguageV0CodeParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] MyLanguageV0CodeParser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyLanguageV0CodeParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] MyLanguageV0CodeParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyLanguageV0CodeParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] MyLanguageV0CodeParser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyLanguageV0CodeParser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInteger([NotNull] MyLanguageV0CodeParser.IntegerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyLanguageV0CodeParser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInteger([NotNull] MyLanguageV0CodeParser.IntegerContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
