//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Poc and Personal\GrammarDemo\SimpleLanguage.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class SimpleLanguageParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, OR=4, AND=5, EQ=6, NEQ=7, GT=8, LT=9, GTEQ=10, 
		LTEQ=11, PLUS=12, MINUS=13, MULT=14, DIV=15, MOD=16, POW=17, NOT=18, SCOL=19, 
		ASSIGN=20, OPAR=21, CPAR=22, OBRACE=23, CBRACE=24, TRUE=25, FALSE=26, 
		NIL=27, IF=28, ELSE=29, WHILE=30, LOG=31, ID=32, INT=33, FLOAT=34, STRING=35, 
		COMMENT=36, SPACE=37, OTHER=38;
	public const int
		RULE_parse = 0, RULE_block = 1, RULE_stat = 2, RULE_assignment = 3, RULE_if_stat = 4, 
		RULE_condition_block = 5, RULE_stat_block = 6, RULE_while_stat = 7, RULE_funDecl = 8, 
		RULE_function = 9, RULE_parameters = 10, RULE_log = 11, RULE_expr = 12, 
		RULE_arguments = 13, RULE_atom = 14;
	public static readonly string[] ruleNames = {
		"parse", "block", "stat", "assignment", "if_stat", "condition_block", 
		"stat_block", "while_stat", "funDecl", "function", "parameters", "log", 
		"expr", "arguments", "atom"
	};

	private static readonly string[] _LiteralNames = {
		null, "'fun'", "'end'", "','", "'||'", "'&&'", "'=='", "'!='", "'>'", 
		"'<'", "'>='", "'<='", "'+'", "'-'", "'*'", "'/'", "'%'", "'^'", "'!'", 
		"';'", "'='", "'('", "')'", "'{'", "'}'", "'true'", "'false'", "'nil'", 
		"'if'", "'else'", "'while'", "'log'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, "OR", "AND", "EQ", "NEQ", "GT", "LT", "GTEQ", 
		"LTEQ", "PLUS", "MINUS", "MULT", "DIV", "MOD", "POW", "NOT", "SCOL", "ASSIGN", 
		"OPAR", "CPAR", "OBRACE", "CBRACE", "TRUE", "FALSE", "NIL", "IF", "ELSE", 
		"WHILE", "LOG", "ID", "INT", "FLOAT", "STRING", "COMMENT", "SPACE", "OTHER"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "SimpleLanguage.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static SimpleLanguageParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public SimpleLanguageParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public SimpleLanguageParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ParseContext : ParserRuleContext {
		public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public ITerminalNode Eof() { return GetToken(SimpleLanguageParser.Eof, 0); }
		public ParseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parse; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterParse(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitParse(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParse(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ParseContext parse() {
		ParseContext _localctx = new ParseContext(Context, State);
		EnterRule(_localctx, 0, RULE_parse);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 30; block();
			State = 31; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockContext : ParserRuleContext {
		public StatContext[] stat() {
			return GetRuleContexts<StatContext>();
		}
		public StatContext stat(int i) {
			return GetRuleContext<StatContext>(i);
		}
		public BlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_block; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterBlock(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitBlock(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BlockContext block() {
		BlockContext _localctx = new BlockContext(Context, State);
		EnterRule(_localctx, 2, RULE_block);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 36;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << IF) | (1L << WHILE) | (1L << LOG) | (1L << ID) | (1L << OTHER))) != 0)) {
				{
				{
				State = 33; stat();
				}
				}
				State = 38;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatContext : ParserRuleContext {
		public IToken _OTHER;
		public AssignmentContext assignment() {
			return GetRuleContext<AssignmentContext>(0);
		}
		public If_statContext if_stat() {
			return GetRuleContext<If_statContext>(0);
		}
		public While_statContext while_stat() {
			return GetRuleContext<While_statContext>(0);
		}
		public FunDeclContext funDecl() {
			return GetRuleContext<FunDeclContext>(0);
		}
		public LogContext log() {
			return GetRuleContext<LogContext>(0);
		}
		public ITerminalNode OTHER() { return GetToken(SimpleLanguageParser.OTHER, 0); }
		public StatContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stat; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterStat(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitStat(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStat(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatContext stat() {
		StatContext _localctx = new StatContext(Context, State);
		EnterRule(_localctx, 4, RULE_stat);
		try {
			State = 46;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case ID:
				EnterOuterAlt(_localctx, 1);
				{
				State = 39; assignment();
				}
				break;
			case IF:
				EnterOuterAlt(_localctx, 2);
				{
				State = 40; if_stat();
				}
				break;
			case WHILE:
				EnterOuterAlt(_localctx, 3);
				{
				State = 41; while_stat();
				}
				break;
			case T__0:
				EnterOuterAlt(_localctx, 4);
				{
				State = 42; funDecl();
				}
				break;
			case LOG:
				EnterOuterAlt(_localctx, 5);
				{
				State = 43; log();
				}
				break;
			case OTHER:
				EnterOuterAlt(_localctx, 6);
				{
				State = 44; _localctx._OTHER = Match(OTHER);
				Console.WriteLine("unknown char: " + (_localctx._OTHER!=null?_localctx._OTHER.Text:null));
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignmentContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(SimpleLanguageParser.ID, 0); }
		public ITerminalNode ASSIGN() { return GetToken(SimpleLanguageParser.ASSIGN, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode SCOL() { return GetToken(SimpleLanguageParser.SCOL, 0); }
		public AssignmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignment; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterAssignment(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitAssignment(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssignment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AssignmentContext assignment() {
		AssignmentContext _localctx = new AssignmentContext(Context, State);
		EnterRule(_localctx, 6, RULE_assignment);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 48; Match(ID);
			State = 49; Match(ASSIGN);
			State = 50; expr(0);
			State = 51; Match(SCOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class If_statContext : ParserRuleContext {
		public ITerminalNode[] IF() { return GetTokens(SimpleLanguageParser.IF); }
		public ITerminalNode IF(int i) {
			return GetToken(SimpleLanguageParser.IF, i);
		}
		public Condition_blockContext[] condition_block() {
			return GetRuleContexts<Condition_blockContext>();
		}
		public Condition_blockContext condition_block(int i) {
			return GetRuleContext<Condition_blockContext>(i);
		}
		public ITerminalNode[] ELSE() { return GetTokens(SimpleLanguageParser.ELSE); }
		public ITerminalNode ELSE(int i) {
			return GetToken(SimpleLanguageParser.ELSE, i);
		}
		public Stat_blockContext stat_block() {
			return GetRuleContext<Stat_blockContext>(0);
		}
		public If_statContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_if_stat; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterIf_stat(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitIf_stat(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIf_stat(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public If_statContext if_stat() {
		If_statContext _localctx = new If_statContext(Context, State);
		EnterRule(_localctx, 8, RULE_if_stat);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 53; Match(IF);
			State = 54; condition_block();
			State = 60;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 55; Match(ELSE);
					State = 56; Match(IF);
					State = 57; condition_block();
					}
					} 
				}
				State = 62;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
			}
			State = 65;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,3,Context) ) {
			case 1:
				{
				State = 63; Match(ELSE);
				State = 64; stat_block();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Condition_blockContext : ParserRuleContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public Stat_blockContext stat_block() {
			return GetRuleContext<Stat_blockContext>(0);
		}
		public Condition_blockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_condition_block; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterCondition_block(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitCondition_block(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCondition_block(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Condition_blockContext condition_block() {
		Condition_blockContext _localctx = new Condition_blockContext(Context, State);
		EnterRule(_localctx, 10, RULE_condition_block);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 67; expr(0);
			State = 68; stat_block();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Stat_blockContext : ParserRuleContext {
		public ITerminalNode OBRACE() { return GetToken(SimpleLanguageParser.OBRACE, 0); }
		public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public ITerminalNode CBRACE() { return GetToken(SimpleLanguageParser.CBRACE, 0); }
		public StatContext stat() {
			return GetRuleContext<StatContext>(0);
		}
		public Stat_blockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stat_block; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterStat_block(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitStat_block(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStat_block(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Stat_blockContext stat_block() {
		Stat_blockContext _localctx = new Stat_blockContext(Context, State);
		EnterRule(_localctx, 12, RULE_stat_block);
		try {
			State = 75;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case OBRACE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 70; Match(OBRACE);
				State = 71; block();
				State = 72; Match(CBRACE);
				}
				break;
			case T__0:
			case IF:
			case WHILE:
			case LOG:
			case ID:
			case OTHER:
				EnterOuterAlt(_localctx, 2);
				{
				State = 74; stat();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class While_statContext : ParserRuleContext {
		public ITerminalNode WHILE() { return GetToken(SimpleLanguageParser.WHILE, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public Stat_blockContext stat_block() {
			return GetRuleContext<Stat_blockContext>(0);
		}
		public While_statContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_while_stat; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterWhile_stat(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitWhile_stat(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitWhile_stat(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public While_statContext while_stat() {
		While_statContext _localctx = new While_statContext(Context, State);
		EnterRule(_localctx, 14, RULE_while_stat);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 77; Match(WHILE);
			State = 78; expr(0);
			State = 79; stat_block();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunDeclContext : ParserRuleContext {
		public FunctionContext function() {
			return GetRuleContext<FunctionContext>(0);
		}
		public FunDeclContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_funDecl; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterFunDecl(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitFunDecl(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunDecl(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunDeclContext funDecl() {
		FunDeclContext _localctx = new FunDeclContext(Context, State);
		EnterRule(_localctx, 16, RULE_funDecl);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 81; Match(T__0);
			State = 82; function();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(SimpleLanguageParser.ID, 0); }
		public ITerminalNode OPAR() { return GetToken(SimpleLanguageParser.OPAR, 0); }
		public ITerminalNode CPAR() { return GetToken(SimpleLanguageParser.CPAR, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ParametersContext parameters() {
			return GetRuleContext<ParametersContext>(0);
		}
		public FunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_function; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterFunction(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitFunction(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionContext function() {
		FunctionContext _localctx = new FunctionContext(Context, State);
		EnterRule(_localctx, 18, RULE_function);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 84; Match(ID);
			State = 85; Match(OPAR);
			State = 87;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ID) {
				{
				State = 86; parameters();
				}
			}

			State = 89; Match(CPAR);
			State = 90; expr(0);
			State = 91; Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParametersContext : ParserRuleContext {
		public ITerminalNode[] ID() { return GetTokens(SimpleLanguageParser.ID); }
		public ITerminalNode ID(int i) {
			return GetToken(SimpleLanguageParser.ID, i);
		}
		public ParametersContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parameters; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterParameters(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitParameters(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParameters(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ParametersContext parameters() {
		ParametersContext _localctx = new ParametersContext(Context, State);
		EnterRule(_localctx, 20, RULE_parameters);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 93; Match(ID);
			State = 98;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__2) {
				{
				{
				State = 94; Match(T__2);
				State = 95; Match(ID);
				}
				}
				State = 100;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LogContext : ParserRuleContext {
		public ITerminalNode LOG() { return GetToken(SimpleLanguageParser.LOG, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode SCOL() { return GetToken(SimpleLanguageParser.SCOL, 0); }
		public LogContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_log; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterLog(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitLog(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLog(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LogContext log() {
		LogContext _localctx = new LogContext(Context, State);
		EnterRule(_localctx, 22, RULE_log);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 101; Match(LOG);
			State = 102; expr(0);
			State = 103; Match(SCOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
	 
		public ExprContext() { }
		public virtual void CopyFrom(ExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class NotExprContext : ExprContext {
		public ITerminalNode NOT() { return GetToken(SimpleLanguageParser.NOT, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public NotExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterNotExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitNotExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNotExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class UnaryMinusExprContext : ExprContext {
		public ITerminalNode MINUS() { return GetToken(SimpleLanguageParser.MINUS, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public UnaryMinusExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterUnaryMinusExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitUnaryMinusExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnaryMinusExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class MultiplicationExprContext : ExprContext {
		public IToken op;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode MULT() { return GetToken(SimpleLanguageParser.MULT, 0); }
		public ITerminalNode DIV() { return GetToken(SimpleLanguageParser.DIV, 0); }
		public ITerminalNode MOD() { return GetToken(SimpleLanguageParser.MOD, 0); }
		public MultiplicationExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterMultiplicationExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitMultiplicationExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMultiplicationExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class AtomExprContext : ExprContext {
		public AtomContext atom() {
			return GetRuleContext<AtomContext>(0);
		}
		public AtomExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterAtomExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitAtomExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAtomExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class OrExprContext : ExprContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode OR() { return GetToken(SimpleLanguageParser.OR, 0); }
		public OrExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterOrExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitOrExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOrExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class AdditiveExprContext : ExprContext {
		public IToken op;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode PLUS() { return GetToken(SimpleLanguageParser.PLUS, 0); }
		public ITerminalNode MINUS() { return GetToken(SimpleLanguageParser.MINUS, 0); }
		public AdditiveExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterAdditiveExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitAdditiveExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAdditiveExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PowExprContext : ExprContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode POW() { return GetToken(SimpleLanguageParser.POW, 0); }
		public PowExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterPowExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitPowExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPowExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RelationalExprContext : ExprContext {
		public IToken op;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode LTEQ() { return GetToken(SimpleLanguageParser.LTEQ, 0); }
		public ITerminalNode GTEQ() { return GetToken(SimpleLanguageParser.GTEQ, 0); }
		public ITerminalNode LT() { return GetToken(SimpleLanguageParser.LT, 0); }
		public ITerminalNode GT() { return GetToken(SimpleLanguageParser.GT, 0); }
		public RelationalExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterRelationalExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitRelationalExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRelationalExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EqualityExprContext : ExprContext {
		public IToken op;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode EQ() { return GetToken(SimpleLanguageParser.EQ, 0); }
		public ITerminalNode NEQ() { return GetToken(SimpleLanguageParser.NEQ, 0); }
		public EqualityExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterEqualityExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitEqualityExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEqualityExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class AndExprContext : ExprContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode AND() { return GetToken(SimpleLanguageParser.AND, 0); }
		public AndExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterAndExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitAndExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAndExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 24;
		EnterRecursionRule(_localctx, 24, RULE_expr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 111;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case MINUS:
				{
				_localctx = new UnaryMinusExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 106; Match(MINUS);
				State = 107; expr(9);
				}
				break;
			case NOT:
				{
				_localctx = new NotExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 108; Match(NOT);
				State = 109; expr(8);
				}
				break;
			case OPAR:
			case TRUE:
			case FALSE:
			case NIL:
			case ID:
			case INT:
			case FLOAT:
			case STRING:
				{
				_localctx = new AtomExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 110; atom();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 136;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,9,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 134;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
					case 1:
						{
						_localctx = new PowExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 113;
						if (!(Precpred(Context, 10))) throw new FailedPredicateException(this, "Precpred(Context, 10)");
						State = 114; Match(POW);
						State = 115; expr(11);
						}
						break;
					case 2:
						{
						_localctx = new MultiplicationExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 116;
						if (!(Precpred(Context, 7))) throw new FailedPredicateException(this, "Precpred(Context, 7)");
						State = 117;
						((MultiplicationExprContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << MULT) | (1L << DIV) | (1L << MOD))) != 0)) ) {
							((MultiplicationExprContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 118; expr(8);
						}
						break;
					case 3:
						{
						_localctx = new AdditiveExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 119;
						if (!(Precpred(Context, 6))) throw new FailedPredicateException(this, "Precpred(Context, 6)");
						State = 120;
						((AdditiveExprContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==PLUS || _la==MINUS) ) {
							((AdditiveExprContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 121; expr(7);
						}
						break;
					case 4:
						{
						_localctx = new RelationalExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 122;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 123;
						((RelationalExprContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << GT) | (1L << LT) | (1L << GTEQ) | (1L << LTEQ))) != 0)) ) {
							((RelationalExprContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 124; expr(6);
						}
						break;
					case 5:
						{
						_localctx = new EqualityExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 125;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 126;
						((EqualityExprContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==EQ || _la==NEQ) ) {
							((EqualityExprContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 127; expr(5);
						}
						break;
					case 6:
						{
						_localctx = new AndExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 128;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 129; Match(AND);
						State = 130; expr(4);
						}
						break;
					case 7:
						{
						_localctx = new OrExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 131;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 132; Match(OR);
						State = 133; expr(3);
						}
						break;
					}
					} 
				}
				State = 138;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,9,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class ArgumentsContext : ParserRuleContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ArgumentsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arguments; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterArguments(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitArguments(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArguments(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgumentsContext arguments() {
		ArgumentsContext _localctx = new ArgumentsContext(Context, State);
		EnterRule(_localctx, 26, RULE_arguments);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 139; expr(0);
			State = 144;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__2) {
				{
				{
				State = 140; Match(T__2);
				State = 141; expr(0);
				}
				}
				State = 146;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AtomContext : ParserRuleContext {
		public AtomContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_atom; } }
	 
		public AtomContext() { }
		public virtual void CopyFrom(AtomContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ParExprContext : AtomContext {
		public ITerminalNode OPAR() { return GetToken(SimpleLanguageParser.OPAR, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode CPAR() { return GetToken(SimpleLanguageParser.CPAR, 0); }
		public ParExprContext(AtomContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterParExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitParExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BooleanAtomContext : AtomContext {
		public ITerminalNode TRUE() { return GetToken(SimpleLanguageParser.TRUE, 0); }
		public ITerminalNode FALSE() { return GetToken(SimpleLanguageParser.FALSE, 0); }
		public BooleanAtomContext(AtomContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterBooleanAtom(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitBooleanAtom(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBooleanAtom(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IdAtomContext : AtomContext {
		public ITerminalNode ID() { return GetToken(SimpleLanguageParser.ID, 0); }
		public IdAtomContext(AtomContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterIdAtom(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitIdAtom(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdAtom(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class StringAtomContext : AtomContext {
		public ITerminalNode STRING() { return GetToken(SimpleLanguageParser.STRING, 0); }
		public StringAtomContext(AtomContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterStringAtom(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitStringAtom(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStringAtom(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NilAtomContext : AtomContext {
		public ITerminalNode NIL() { return GetToken(SimpleLanguageParser.NIL, 0); }
		public NilAtomContext(AtomContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterNilAtom(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitNilAtom(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNilAtom(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumberAtomContext : AtomContext {
		public ITerminalNode INT() { return GetToken(SimpleLanguageParser.INT, 0); }
		public ITerminalNode FLOAT() { return GetToken(SimpleLanguageParser.FLOAT, 0); }
		public NumberAtomContext(AtomContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterNumberAtom(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitNumberAtom(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberAtom(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AtomContext atom() {
		AtomContext _localctx = new AtomContext(Context, State);
		EnterRule(_localctx, 28, RULE_atom);
		int _la;
		try {
			State = 156;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case OPAR:
				_localctx = new ParExprContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 147; Match(OPAR);
				State = 148; expr(0);
				State = 149; Match(CPAR);
				}
				break;
			case INT:
			case FLOAT:
				_localctx = new NumberAtomContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 151;
				_la = TokenStream.LA(1);
				if ( !(_la==INT || _la==FLOAT) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				break;
			case TRUE:
			case FALSE:
				_localctx = new BooleanAtomContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 152;
				_la = TokenStream.LA(1);
				if ( !(_la==TRUE || _la==FALSE) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				break;
			case ID:
				_localctx = new IdAtomContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 153; Match(ID);
				}
				break;
			case STRING:
				_localctx = new StringAtomContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 154; Match(STRING);
				}
				break;
			case NIL:
				_localctx = new NilAtomContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 155; Match(NIL);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 12: return expr_sempred((ExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 10);
		case 1: return Precpred(Context, 7);
		case 2: return Precpred(Context, 6);
		case 3: return Precpred(Context, 5);
		case 4: return Precpred(Context, 4);
		case 5: return Precpred(Context, 3);
		case 6: return Precpred(Context, 2);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '(', '\xA1', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\a', '\x3', '%', '\n', 
		'\x3', '\f', '\x3', '\xE', '\x3', '(', '\v', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x5', '\x4', '\x31', '\n', '\x4', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\a', '\x6', '=', '\n', '\x6', 
		'\f', '\x6', '\xE', '\x6', '@', '\v', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x5', '\x6', '\x44', '\n', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x5', 
		'\b', 'N', '\n', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x5', '\v', 'Z', '\n', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\a', '\f', '\x63', 
		'\n', '\f', '\f', '\f', '\xE', '\f', '\x66', '\v', '\f', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x5', '\xE', 'r', '\n', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\a', '\xE', '\x89', '\n', '\xE', '\f', '\xE', '\xE', 
		'\xE', '\x8C', '\v', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\a', '\xF', '\x91', '\n', '\xF', '\f', '\xF', '\xE', '\xF', '\x94', '\v', 
		'\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x5', 
		'\x10', '\x9F', '\n', '\x10', '\x3', '\x10', '\x2', '\x3', '\x1A', '\x11', 
		'\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', '\x12', '\x14', 
		'\x16', '\x18', '\x1A', '\x1C', '\x1E', '\x2', '\b', '\x3', '\x2', '\x10', 
		'\x12', '\x3', '\x2', '\xE', '\xF', '\x3', '\x2', '\n', '\r', '\x3', '\x2', 
		'\b', '\t', '\x3', '\x2', '#', '$', '\x3', '\x2', '\x1B', '\x1C', '\x2', 
		'\xAB', '\x2', ' ', '\x3', '\x2', '\x2', '\x2', '\x4', '&', '\x3', '\x2', 
		'\x2', '\x2', '\x6', '\x30', '\x3', '\x2', '\x2', '\x2', '\b', '\x32', 
		'\x3', '\x2', '\x2', '\x2', '\n', '\x37', '\x3', '\x2', '\x2', '\x2', 
		'\f', '\x45', '\x3', '\x2', '\x2', '\x2', '\xE', 'M', '\x3', '\x2', '\x2', 
		'\x2', '\x10', 'O', '\x3', '\x2', '\x2', '\x2', '\x12', 'S', '\x3', '\x2', 
		'\x2', '\x2', '\x14', 'V', '\x3', '\x2', '\x2', '\x2', '\x16', '_', '\x3', 
		'\x2', '\x2', '\x2', '\x18', 'g', '\x3', '\x2', '\x2', '\x2', '\x1A', 
		'q', '\x3', '\x2', '\x2', '\x2', '\x1C', '\x8D', '\x3', '\x2', '\x2', 
		'\x2', '\x1E', '\x9E', '\x3', '\x2', '\x2', '\x2', ' ', '!', '\x5', '\x4', 
		'\x3', '\x2', '!', '\"', '\a', '\x2', '\x2', '\x3', '\"', '\x3', '\x3', 
		'\x2', '\x2', '\x2', '#', '%', '\x5', '\x6', '\x4', '\x2', '$', '#', '\x3', 
		'\x2', '\x2', '\x2', '%', '(', '\x3', '\x2', '\x2', '\x2', '&', '$', '\x3', 
		'\x2', '\x2', '\x2', '&', '\'', '\x3', '\x2', '\x2', '\x2', '\'', '\x5', 
		'\x3', '\x2', '\x2', '\x2', '(', '&', '\x3', '\x2', '\x2', '\x2', ')', 
		'\x31', '\x5', '\b', '\x5', '\x2', '*', '\x31', '\x5', '\n', '\x6', '\x2', 
		'+', '\x31', '\x5', '\x10', '\t', '\x2', ',', '\x31', '\x5', '\x12', '\n', 
		'\x2', '-', '\x31', '\x5', '\x18', '\r', '\x2', '.', '/', '\a', '(', '\x2', 
		'\x2', '/', '\x31', '\b', '\x4', '\x1', '\x2', '\x30', ')', '\x3', '\x2', 
		'\x2', '\x2', '\x30', '*', '\x3', '\x2', '\x2', '\x2', '\x30', '+', '\x3', 
		'\x2', '\x2', '\x2', '\x30', ',', '\x3', '\x2', '\x2', '\x2', '\x30', 
		'-', '\x3', '\x2', '\x2', '\x2', '\x30', '.', '\x3', '\x2', '\x2', '\x2', 
		'\x31', '\a', '\x3', '\x2', '\x2', '\x2', '\x32', '\x33', '\a', '\"', 
		'\x2', '\x2', '\x33', '\x34', '\a', '\x16', '\x2', '\x2', '\x34', '\x35', 
		'\x5', '\x1A', '\xE', '\x2', '\x35', '\x36', '\a', '\x15', '\x2', '\x2', 
		'\x36', '\t', '\x3', '\x2', '\x2', '\x2', '\x37', '\x38', '\a', '\x1E', 
		'\x2', '\x2', '\x38', '>', '\x5', '\f', '\a', '\x2', '\x39', ':', '\a', 
		'\x1F', '\x2', '\x2', ':', ';', '\a', '\x1E', '\x2', '\x2', ';', '=', 
		'\x5', '\f', '\a', '\x2', '<', '\x39', '\x3', '\x2', '\x2', '\x2', '=', 
		'@', '\x3', '\x2', '\x2', '\x2', '>', '<', '\x3', '\x2', '\x2', '\x2', 
		'>', '?', '\x3', '\x2', '\x2', '\x2', '?', '\x43', '\x3', '\x2', '\x2', 
		'\x2', '@', '>', '\x3', '\x2', '\x2', '\x2', '\x41', '\x42', '\a', '\x1F', 
		'\x2', '\x2', '\x42', '\x44', '\x5', '\xE', '\b', '\x2', '\x43', '\x41', 
		'\x3', '\x2', '\x2', '\x2', '\x43', '\x44', '\x3', '\x2', '\x2', '\x2', 
		'\x44', '\v', '\x3', '\x2', '\x2', '\x2', '\x45', '\x46', '\x5', '\x1A', 
		'\xE', '\x2', '\x46', 'G', '\x5', '\xE', '\b', '\x2', 'G', '\r', '\x3', 
		'\x2', '\x2', '\x2', 'H', 'I', '\a', '\x19', '\x2', '\x2', 'I', 'J', '\x5', 
		'\x4', '\x3', '\x2', 'J', 'K', '\a', '\x1A', '\x2', '\x2', 'K', 'N', '\x3', 
		'\x2', '\x2', '\x2', 'L', 'N', '\x5', '\x6', '\x4', '\x2', 'M', 'H', '\x3', 
		'\x2', '\x2', '\x2', 'M', 'L', '\x3', '\x2', '\x2', '\x2', 'N', '\xF', 
		'\x3', '\x2', '\x2', '\x2', 'O', 'P', '\a', ' ', '\x2', '\x2', 'P', 'Q', 
		'\x5', '\x1A', '\xE', '\x2', 'Q', 'R', '\x5', '\xE', '\b', '\x2', 'R', 
		'\x11', '\x3', '\x2', '\x2', '\x2', 'S', 'T', '\a', '\x3', '\x2', '\x2', 
		'T', 'U', '\x5', '\x14', '\v', '\x2', 'U', '\x13', '\x3', '\x2', '\x2', 
		'\x2', 'V', 'W', '\a', '\"', '\x2', '\x2', 'W', 'Y', '\a', '\x17', '\x2', 
		'\x2', 'X', 'Z', '\x5', '\x16', '\f', '\x2', 'Y', 'X', '\x3', '\x2', '\x2', 
		'\x2', 'Y', 'Z', '\x3', '\x2', '\x2', '\x2', 'Z', '[', '\x3', '\x2', '\x2', 
		'\x2', '[', '\\', '\a', '\x18', '\x2', '\x2', '\\', ']', '\x5', '\x1A', 
		'\xE', '\x2', ']', '^', '\a', '\x4', '\x2', '\x2', '^', '\x15', '\x3', 
		'\x2', '\x2', '\x2', '_', '\x64', '\a', '\"', '\x2', '\x2', '`', '\x61', 
		'\a', '\x5', '\x2', '\x2', '\x61', '\x63', '\a', '\"', '\x2', '\x2', '\x62', 
		'`', '\x3', '\x2', '\x2', '\x2', '\x63', '\x66', '\x3', '\x2', '\x2', 
		'\x2', '\x64', '\x62', '\x3', '\x2', '\x2', '\x2', '\x64', '\x65', '\x3', 
		'\x2', '\x2', '\x2', '\x65', '\x17', '\x3', '\x2', '\x2', '\x2', '\x66', 
		'\x64', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\a', '!', '\x2', '\x2', 
		'h', 'i', '\x5', '\x1A', '\xE', '\x2', 'i', 'j', '\a', '\x15', '\x2', 
		'\x2', 'j', '\x19', '\x3', '\x2', '\x2', '\x2', 'k', 'l', '\b', '\xE', 
		'\x1', '\x2', 'l', 'm', '\a', '\xF', '\x2', '\x2', 'm', 'r', '\x5', '\x1A', 
		'\xE', '\v', 'n', 'o', '\a', '\x14', '\x2', '\x2', 'o', 'r', '\x5', '\x1A', 
		'\xE', '\n', 'p', 'r', '\x5', '\x1E', '\x10', '\x2', 'q', 'k', '\x3', 
		'\x2', '\x2', '\x2', 'q', 'n', '\x3', '\x2', '\x2', '\x2', 'q', 'p', '\x3', 
		'\x2', '\x2', '\x2', 'r', '\x8A', '\x3', '\x2', '\x2', '\x2', 's', 't', 
		'\f', '\f', '\x2', '\x2', 't', 'u', '\a', '\x13', '\x2', '\x2', 'u', '\x89', 
		'\x5', '\x1A', '\xE', '\r', 'v', 'w', '\f', '\t', '\x2', '\x2', 'w', 'x', 
		'\t', '\x2', '\x2', '\x2', 'x', '\x89', '\x5', '\x1A', '\xE', '\n', 'y', 
		'z', '\f', '\b', '\x2', '\x2', 'z', '{', '\t', '\x3', '\x2', '\x2', '{', 
		'\x89', '\x5', '\x1A', '\xE', '\t', '|', '}', '\f', '\a', '\x2', '\x2', 
		'}', '~', '\t', '\x4', '\x2', '\x2', '~', '\x89', '\x5', '\x1A', '\xE', 
		'\b', '\x7F', '\x80', '\f', '\x6', '\x2', '\x2', '\x80', '\x81', '\t', 
		'\x5', '\x2', '\x2', '\x81', '\x89', '\x5', '\x1A', '\xE', '\a', '\x82', 
		'\x83', '\f', '\x5', '\x2', '\x2', '\x83', '\x84', '\a', '\a', '\x2', 
		'\x2', '\x84', '\x89', '\x5', '\x1A', '\xE', '\x6', '\x85', '\x86', '\f', 
		'\x4', '\x2', '\x2', '\x86', '\x87', '\a', '\x6', '\x2', '\x2', '\x87', 
		'\x89', '\x5', '\x1A', '\xE', '\x5', '\x88', 's', '\x3', '\x2', '\x2', 
		'\x2', '\x88', 'v', '\x3', '\x2', '\x2', '\x2', '\x88', 'y', '\x3', '\x2', 
		'\x2', '\x2', '\x88', '|', '\x3', '\x2', '\x2', '\x2', '\x88', '\x7F', 
		'\x3', '\x2', '\x2', '\x2', '\x88', '\x82', '\x3', '\x2', '\x2', '\x2', 
		'\x88', '\x85', '\x3', '\x2', '\x2', '\x2', '\x89', '\x8C', '\x3', '\x2', 
		'\x2', '\x2', '\x8A', '\x88', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', 
		'\x3', '\x2', '\x2', '\x2', '\x8B', '\x1B', '\x3', '\x2', '\x2', '\x2', 
		'\x8C', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x92', '\x5', '\x1A', 
		'\xE', '\x2', '\x8E', '\x8F', '\a', '\x5', '\x2', '\x2', '\x8F', '\x91', 
		'\x5', '\x1A', '\xE', '\x2', '\x90', '\x8E', '\x3', '\x2', '\x2', '\x2', 
		'\x91', '\x94', '\x3', '\x2', '\x2', '\x2', '\x92', '\x90', '\x3', '\x2', 
		'\x2', '\x2', '\x92', '\x93', '\x3', '\x2', '\x2', '\x2', '\x93', '\x1D', 
		'\x3', '\x2', '\x2', '\x2', '\x94', '\x92', '\x3', '\x2', '\x2', '\x2', 
		'\x95', '\x96', '\a', '\x17', '\x2', '\x2', '\x96', '\x97', '\x5', '\x1A', 
		'\xE', '\x2', '\x97', '\x98', '\a', '\x18', '\x2', '\x2', '\x98', '\x9F', 
		'\x3', '\x2', '\x2', '\x2', '\x99', '\x9F', '\t', '\x6', '\x2', '\x2', 
		'\x9A', '\x9F', '\t', '\a', '\x2', '\x2', '\x9B', '\x9F', '\a', '\"', 
		'\x2', '\x2', '\x9C', '\x9F', '\a', '%', '\x2', '\x2', '\x9D', '\x9F', 
		'\a', '\x1D', '\x2', '\x2', '\x9E', '\x95', '\x3', '\x2', '\x2', '\x2', 
		'\x9E', '\x99', '\x3', '\x2', '\x2', '\x2', '\x9E', '\x9A', '\x3', '\x2', 
		'\x2', '\x2', '\x9E', '\x9B', '\x3', '\x2', '\x2', '\x2', '\x9E', '\x9C', 
		'\x3', '\x2', '\x2', '\x2', '\x9E', '\x9D', '\x3', '\x2', '\x2', '\x2', 
		'\x9F', '\x1F', '\x3', '\x2', '\x2', '\x2', '\xE', '&', '\x30', '>', '\x43', 
		'M', 'Y', '\x64', 'q', '\x88', '\x8A', '\x92', '\x9E',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
